version: "3.9"

services:
  cudos-node:
    build:
      dockerfile: cudos-node.dockerfile
      context: ./
    ports:
      - "1317:1317"
      - "26657:26657"
    volumes:
      - cudos_data:/usr/cudos/cudos-data

volumes:
  cudos_data:
