on: pull_request
name: Code Checks

jobs:
  check-code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repository and checkout branch
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: 16
      - run: npm install
        name: Install root dependencies
      - run: npm run lint
        name: Run a linter check
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repository and checkout branch
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: 16
      - run: npm install && npm run install-cmd
        name: Install blast-core dependencies and blast as a global command
      - run: npm run test
        name: Run e2e tests