on: pull_request
name: Run tests

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Clone repository and checkout branch
      - uses: actions/setup-node@v2
        name: Setup node.js
        with:
          node-version: 16
      - run: npm install && npm install -g
        name: Install dependencies
      - run: npm run test
        name: Run tests